name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Case 1 [Dave, 12345, abc123]
      id: test-case-1-dave-12345-abc123
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 1 [Dave, 12345, abc123]
        setup-command: ''
        command: python3 cyber_suite_new_user.py
        input: |-
          Dave
          12345
          abc123
        expected-output: "Please enter your name: Please enter your user id: Please
          enter your password: \nWelcome, Dave. Your ID is 12345.\n\nPASSWORD: \nXXXXXX"
        comparison-method: exact
        timeout: 10
        max-score: 7
    - name: Test Case 2 [Katie, 13090, PCT2024]
      id: test-case-2-katie-13090-pct2024
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 2 [Katie, 13090, PCT2024]
        setup-command: ''
        command: python3 cyber_suite_new_user.py
        input: |-
          Katie
          13090
          PCT2024
        expected-output: "Please enter your name: Please enter your user id: Please
          enter your password: \nWelcome, Katie. Your ID is 13090.\n\nPASSWORD: \nXXXXXXX"
        comparison-method: exact
        timeout: 10
        max-score: 7
    - name: Test Case 3 [John, 10008, TheOtherDayISawABearAGreatBigBear]
      id: test-case-3-john-10008-theotherdayisawabearagreatbigbear
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 3 [John, 10008, TheOtherDayISawABearAGreatBigBear]
        setup-command: ''
        command: python3 cyber_suite_new_user.py
        input: |-
          John
          10008
          TheOtherDayISawABearAGreatBigBear
        expected-output: "Please enter your name: Please enter your user id: Please
          enter your password: \nWelcome, John. Your ID is 10008.\n\nPASSWORD: \nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        comparison-method: contains
        timeout: 10
        max-score: 6
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CASE-1-DAVE-12345-ABC123_RESULTS: "${{steps.test-case-1-dave-12345-abc123.outputs.result}}"
        TEST-CASE-2-KATIE-13090-PCT2024_RESULTS: "${{steps.test-case-2-katie-13090-pct2024.outputs.result}}"
        TEST-CASE-3-JOHN-10008-THEOTHERDAYISAWABEARAGREATBIGBEAR_RESULTS: "${{steps.test-case-3-john-10008-theotherdayisawabearagreatbigbear.outputs.result}}"
      with:
        runners: test-case-1-dave-12345-abc123,test-case-2-katie-13090-pct2024,test-case-3-john-10008-theotherdayisawabearagreatbigbear
